apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    user: frauduser
    secureJsonData:
      password: fraudpass123
    jsonData:
      database: frauddb
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
